In [118]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
%matplotlib inline
import  matplotlib.pyplot as plt
import joblib
from sklearn.metrics import mean_absolute_percentage_error
import random
import torch
import os

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
seed_everything(seed=521)

In [119]:
train=pd.read_csv("../train_com.csv")
train.describe()

,L,V,DO,E,pH,TOC,TN,C/N,C/S,SO4,H2S
count,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000
mean,5.461929,0.226688,0.945984,962.086294,7.347244,36.995184,16.058581,2.342726,0.616699,61.555513,16.815631
std,2.339724,0.090990,0.645469,78.275336,0.097261,21.433798,5.695426,0.998732,0.384182,13.670856,16.292675
min,1.000000,0.097224,0.020000,745.000000,7.100000,9.321598,6.243985,0.941765,0.225891,35.936300,0.010000
25%,4.000000,0.160000,0.320000,922.000000,7.285419,21.735546,11.708600,1.556026,0.356042,48.994313,2.750000
50%,6.000000,0.216000,0.960000,974.000000,7.330000,32.673277,15.238409,2.109702,0.510619,61.358200,7.280000
75%,7.000000,0.276000,1.420000,1021.000000,7.380000,48.120133,20.050361,3.076531,0.819627,70.593543,32.780800
max,9.000000,0.558000,2.540000,1100.000000,7.700000,155.442607,40.117917,5.704046,3.945414,98.179500,50.590173

In [120]:
test=pd.read_csv("../test1.csv")
test.describe()

,L,V,DO,E,pH,TOC,TN,C/N,C/S,SO4,H2S
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,5.791667,0.195000,1.114167,954.000000,7.356667,33.082966,16.421136,2.065140,0.538394,63.681004,30.175000
std,2.264646,0.074305,0.661999,83.173993,0.107851,17.205562,6.707066,0.855174,0.304127,13.195245,17.598888
min,1.000000,0.102000,0.120000,807.000000,7.200000,9.727586,5.973685,0.931152,0.166123,36.481900,0.010000
25%,6.000000,0.139250,0.390000,895.000000,7.270000,21.539393,12.769102,1.383196,0.326058,59.029075,15.787500
50%,7.000000,0.166000,1.250000,960.000000,7.320000,28.351351,15.669401,2.012730,0.472753,64.461800,33.250000
75%,7.000000,0.235750,1.650000,1006.750000,7.440000,45.563246,18.390176,2.669494,0.721353,69.482000,46.580000
max,9.000000,0.351000,2.250000,1074.000000,7.610000,84.636852,40.117917,4.231449,1.420067,98.179500,50.000000

In [121]:
train=np.array(train)
test=np.array(test)
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split


train_x_1=train[:,:10]
train_y_1=train[:,10]
test_x_1=test[:,:10]
test_y_1=test[:,10]

scaler1=MinMaxScaler()
scaler2=MinMaxScaler()
scaler3=MinMaxScaler()
scaler4=MinMaxScaler()

train_x=scaler1.fit_transform(train_x_1)
train_y=scaler2.fit_transform(np.reshape(train_y_1,(-1,1)))
test_x=scaler3.fit_transform(test_x_1)
test_y=scaler4.fit_transform(np.reshape(test_y_1,(-1,1)))

In [122]:
from sklearn.linear_model import TheilSenRegressor

model = TheilSenRegressor(random_state=10) # 线性回归
model.fit(train_x,train_y)

TheilSenRegressor(random_state=10)

In [123]:
pre=model.predict(test_x)
print(pre)

pre=scaler4.inverse_transform(np.reshape(pre,(-1,1)))

[-0.20237916  1.0899722  -0.27972311  0.06118879  0.27543761  0.34748789
  0.23374965  1.18180119  0.68351132  0.52010493  0.86260423  0.63477585
  0.06600675  0.42993128  0.39482486  0.74809317  0.62746887  0.88449587
  1.14392782  1.55388495  1.6640927   1.12427153  1.18180119  0.52010493]

In [124]:
from math import sqrt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
MAE=mean_absolute_error(test_y_1, pre)
MSE=mean_squared_error(test_y_1, pre)
RMSE=sqrt(mean_squared_error(test_y_1,pre))
R2=r2_score(test_y_1,pre)
print("mean_absolute_error:", mean_absolute_error(test_y_1, pre))
print("mean_squared_error:", mean_squared_error(test_y_1, pre))
print("rmse:", sqrt(mean_squared_error(test_y_1, pre)))
print("r2 score:", r2_score(test_y_1, pre))

mean_absolute_error: 13.928791213392088
mean_squared_error: 367.1776206382265
rmse: 19.161879360809746
r2 score: -0.23705537037801716

In [125]:
results = {
    'Metric': ['mean_absolute_error', 'mean_squared_error', 'rmse', 'r2 score'],
    'Value': [MAE, MSE, RMSE, R2]
}
# 使用Pandas创建一个数据框
results_df = pd.DataFrame(results)

# 打印数据框
print(results_df)
results_df.to_csv('16.csv', index=False)

                Metric       Value
0  mean_absolute_error   13.928791
1   mean_squared_error  367.177621
2                 rmse   19.161879
3             r2 score   -0.237055

In [126]:
datapre=np.asarray(pre)
datapre.tofile('16-pre.csv',sep=',',format='%10.5f')